# Docker Compose configuration for WordPress application stack

version: "3"

services:
  # MariaDB service for the database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    expose:
      - "3306"

  # WordPress service
  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: on-failure
    expose:
      - "9000"

  # NGINX service for the web server
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: on-failure
    ports:
      - "443:443"

volumes:
  # Volume for WordPress data
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/egiacomi/data/wordpress'

  # Volume for MariaDB data
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/egiacomi/data/mariadb'

networks:
  # Custom network for communication between services
  inception:
    driver: bridge
